apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: 2cloud
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"

spec:
  backoffLimit: 3

  template:
    spec:
      imagePullSecrets:
        - name: dockerhub-2cloud

      restartPolicy: Never

      containers:
        - name: migrate
          image: shaheeradmin/2cloud-next-js:46772a7d3882b829203ea6b114ca74f8168c1d23
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -c
            - |
              npx prisma migrate deploy && npx prisma db seed

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: DATABASE_URL
              value: "postgresql://twocloud:$(POSTGRES_PASSWORD)@postgres:5432/twocloud_prod"

            - name: ADMIN_SEED_EMAIL
              value: "admin@localhost"

            - name: ADMIN_SEED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: ADMIN_SEED_PASSWORD
